# -*- coding: utf-8 -*-
"""Procesamiento River.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ZS5G6ZMRByp-WWB-G2-aznn1mZQepNd
"""

#@title Procesamiento River { display-mode: "form" }
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()
import pandas as pd
import numpy as np
!pip install xlsxwriter
import xlsxwriter

gc = gspread.authorize(creds)
pd.set_option('display.max_columns',None)


#  leer un google sheet
URL_del_Google_Sheet = "https://docs.google.com/spreadsheets/d/14BYiCl916OXra4WkLlsW75Gquyazf5KpUzABLUuJmYk/edit#gid=0" #@param {type: "string"}
wk = gc.open_by_url(URL_del_Google_Sheet)
# declarar y asignar la hoja a usar de dicho google sheet
Nombre_de_la_primer_hoja = "Hoja 1" #@param {type: "string"}
wsLibroIva = wk.worksheet(Nombre_de_la_primer_hoja)
Nombre_de_la_segunda_hoja = "Hoja 2" #@param {type: "string"}
wsLibroIva2 = wk.worksheet(Nombre_de_la_segunda_hoja)

# verificacion validacion columna fila
def SheetToList(sheet):
  rowsLi = sheet.get_all_values()
  dfLi = pd.DataFrame.from_records(rowsLi[1:],columns=rowsLi[0])
  dfLi = dfLi[sorted(dfLi.columns)]
  return dfLi

def VerifyCols(df):
  # verificar que se encuentren todas las columnas, sino agregar las faltantes
  dfCol = df.columns.tolist()
  dfColRes = []
  totalCols =  ['', '01. Zona Alta:ZONA 11', '01. Zona Alta:ZONA 12', '01. Zona Alta:ZONA 13', '01. Zona Alta:ZONA 14', '01. Zona Alta:ZONA 15', '01. Zona Baja:ZONA 1', '01. Zona Baja:ZONA 2', '01. Zona Baja:ZONA 3', '01. Zona Baja:ZONA 4', '01. Zona Baja:ZONA 5', '01. Zona Media:ZONA 10', '01. Zona Media:ZONA 6', '01. Zona Media:ZONA 7', '01. Zona Media:ZONA 8', '01. Zona Media:ZONA 9', '01. Zona de Inicio:PASE', '02. Zona Media:ZONA 10', '02. Zona Media:ZONA 6' ,'02. Zona Media:ZONA 7', '02. Zona Media:ZONA 8', '02. Zona Media:ZONA 9', '03. Zona Alta:ZONA 11', '03. Zona Alta:ZONA 12', '03. Zona Alta:ZONA 13', '03. Zona Alta:ZONA 14', '03. Zona Alta:ZONA 15', '04. Perdida:CONTROL', '04. Perdida:GAMBETA', '04. Perdida:PERFIL']
  if dfCol != totalCols:
    # si hay columnas faltantes se agregan
    missingCols = np.setdiff1d(totalCols, dfCol, assume_unique=False)
    for i in missingCols:
      df[i] = 0
  return df[sorted(df.columns)]

def VerifyRows(df):
  # verificar que se encuentren todas las columnas, sino agregar las faltantes
  dfRow = df[''].tolist()
  dfColRes = []
  totalRows =  ['APROXIMACION RIVAL','APROXIMACION RIVER','ATAQUE RIVAL','ATAQUE RIVER','CORNER','CORNER RIVAL','DEFINICION RIVER','DEFINICION RIVAL','GOL RIVER','GOL RIVAL','PERDIDA','PENALES RIVER','PENALES RIVAL','RECUPERACION','TIRO LIBRE','TIRO LIBRE RIVAL','SALIDAS RIVER','SALIDAS RIVAL']
  if dfRow != totalRows:
    # si hay columnas faltantes se agregan
    missingRows = np.setdiff1d(totalRows, dfRow, assume_unique=False)
    for i in missingRows:
      df.loc[len(df)] = i
      df.loc[len(df) - 1, 1:] = 0
  return df

# conversion de input y verificación de filas y colmunas
dfLi =  SheetToList(wsLibroIva)
dfLi2 =   SheetToList(wsLibroIva2)
dfLiVerif = VerifyCols(dfLi)
dfLiVerif2 = VerifyCols(dfLi2)
dfLiVerif = VerifyRows(dfLiVerif)
dfLiVerif2 = VerifyRows(dfLiVerif2)
dfLiVerif = dfLiVerif.sort_values(by=[''])
dfLiVerif2 = dfLiVerif2.sort_values(by=[''])
dfLiVerif = dfLiVerif.reset_index(inplace=False, drop=True)
dfLiVerif2 = dfLiVerif2.reset_index(inplace=False, drop=True)

# concatenacion y transposición
dfLiTotal = pd.concat([dfLiVerif, dfLiVerif2.iloc[:, 1:]], axis=1,sort=True)
dfLiTransp = dfLiTotal.transpose()
df = pd.DataFrame(dfLiTransp)

# agregar 3 columnas, iterar sobre primer columna de df y segun el valor se componen el resto de los valores
df.insert(loc= 0 , column= 'PROFUNIDAD',value=0)
df.insert(loc= 1 , column= 'AMPLITUD',value=0)
df.insert(loc= 2 , column= 'NUM ZONA',value=0)
df.insert(loc= 3 , column= 'CONTENIDO',value=0)
df['PROFUNIDAD'][0] = 'PROFUNIDAD'
df['AMPLITUD'][0] = 'AMPLITUD'
df['NUM ZONA'][0] = 'NUM ZONA'
df['CONTENIDO'][0] = 'CONTENIDO'

# REESTRUCTURACION DE INFORMACION ZONA EN PROFUNDIDAD, AMPLITUD, NUM ZONA, CONTENIDO
for (label, content) in df.iteritems():
  if label == 0:
    pr = 'PROFUNDIDAD'
    am = 'AMPLITUD'
    nz = 'NUM ZONA'
    for i in range(1, 30):
      if df.index.values[i] == '01. Zona Alta:ZONA 11':
        df.iat[i,0] = 'Zona Alta'
        df.iat[i,1] = 'BANDA DERECHA'
        df.iat[i,2] = '11'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 12':
        df.iat[i,0] = 'Zona Alta'
        df.iat[i,1] = 'PASILLO DERECHO'
        df.iat[i,2] = '12'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 13':
        df.iat[i,0] = 'Zona Alta'
        df.iat[i,1] = 'EJE'
        df.iat[i,2] = '13'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 14':
        df.iat[i,0] = 'Zona Alta'
        df.iat[i,1] = 'PASILLO IZQUIERDO'
        df.iat[i,2] = '14'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 15':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '15'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 1':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '1'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 2':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '2'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 3':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '3'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 4':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '4'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 5':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '5'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 10':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '10'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 6':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '6'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 7':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '7'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 8':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '8'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 9':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '9'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona de Inicio:PASE':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = 'Inicio'
        df.iat[i,3] = 'PASE'
      if df.index.values[i] == '02. Zona Media:ZONA 10':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '10'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 6':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '6'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 7':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '7'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 8':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '8'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 9':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '9'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 11':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '11'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 12':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '12'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 13':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '13'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 14':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '14'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 15':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '15'
        df.iat[i,3] = ''
      if df.index.values[i] == '04. Perdida:CONTROL':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = ''
        df.iat[i,3] = 'CONTROL'
      if df.index.values[i] == '04. Perdida:GAMBETA':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = ''
        df.iat[i,3] = 'GAMBETA'
      if df.index.values[i] == '04. Perdida:PERFIL':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = ''
        df.iat[i,3] = 'PERFIL'
    # segundo tiempo
    for i in range(30, 59):
      if df.index.values[i] == '01. Zona Alta:ZONA 11':
        df.iat[i,0] = 'Zona Baja'
        df.iat[i,1] = 'BANDA IZQUIERDA'
        df.iat[i,2] = '5'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 12':
        df.iat[i,0] = 'Zona Baja'
        df.iat[i,1] = 'PASILLO IZQUIERDO'
        df.iat[i,2] = '4'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 13':
        df.iat[i,0] = 'Zona Baja'
        df.iat[i,1] = 'EJE'
        df.iat[i,2] = '3'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 14':
        df.iat[i,0] = 'Zona Baja'
        df.iat[i,1] = 'PASILLO IZQUIERDO'
        df.iat[i,2] = '2'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Alta:ZONA 15':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '1'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 1':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '15'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 2':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '14'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 3':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '13'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 4':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '12'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Baja:ZONA 5':
        df.iloc[i,0] = 'Zona Alta'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '11'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 10':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '6'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 6':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '10'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 7':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '9'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 8':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '8'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona Media:ZONA 9':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '7'
        df.iat[i,3] = ''
      if df.index.values[i] == '01. Zona de Inicio:PASE':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = 'Inicio'
        df.iat[i,3] = 'PASE'
      if df.index.values[i] == '02. Zona Media:ZONA 10':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '6'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 6':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '10'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 7':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '9'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 8':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '8'
        df.iat[i,3] = ''
      if df.index.values[i] == '02. Zona Media:ZONA 9':
        df.iloc[i,0] = 'Zona Media'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '7'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 11':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'BANDA IZQUIERDA'
        df.iloc[i,2] = '5'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 12':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'PASILLO IZQUIERDO'
        df.iloc[i,2] = '4'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 13':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'EJE'
        df.iloc[i,2] = '3'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 14':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'PASILLO DERECHO'
        df.iloc[i,2] = '2'
        df.iat[i,3] = ''
      if df.index.values[i] == '03. Zona Alta:ZONA 15':
        df.iloc[i,0] = 'Zona Baja'
        df.iloc[i,1] = 'BANDA DERECHA'
        df.iloc[i,2] = '1'
        df.iat[i,3] = ''
      if df.index.values[i] == '04. Perdida:CONTROL':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = ''
        df.iat[i,3] = 'CONTROL'
      if df.index.values[i] == '04. Perdida:GAMBETA':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = ''
        df.iat[i,3] = 'GAMBETA'
      if df.index.values[i] == '04. Perdida:PERFIL':
        df.iloc[i,0] = ''
        df.iloc[i,1] = ''
        df.iloc[i,2] = ''
        df.iat[i,3] = 'PERFIL'

# agregado de perdidas por contenido
df.insert(loc=len(df.columns), column= 'PERDIDAS POR CONTENIDO',value='')
df['PERDIDAS POR CONTENIDO'][0] = 'PERDIDAS POR CONTENIDO'

# correccion valores de perdidas por contendio
df['PERDIDAS POR CONTENIDO'][16] = df[12][16]
df[12][16] = 0
df['PERDIDAS POR CONTENIDO'][27] = df[12][27]
df[12][27] = 0
df['PERDIDAS POR CONTENIDO'][28] = df[12][28]
df[12][28] = 0
df['PERDIDAS POR CONTENIDO'][29] = df[12][29]
df[12][29] = 0
df['PERDIDAS POR CONTENIDO'][45] = df[12][45]
df[12][45] = 0
df['PERDIDAS POR CONTENIDO'][56] = df[12][56]
df[12][56] = 0
df['PERDIDAS POR CONTENIDO'][57] = df[12][57]
df[12][57] = 0
df['PERDIDAS POR CONTENIDO'][58] = df[12][58]
df[12][58] = 0

# formateo a excel
writer = pd.ExcelWriter("Resultado Partido.xlsx", engine='xlsxwriter')
df.to_excel(writer, sheet_name='Hoja1', columns=None, header=False, index=False)

workbook  = writer.book
worksheet = writer.sheets['Hoja1']

formato_titulo = workbook.add_format({
  'bold': 1,
  'border': 1,
  'align': 'center',
  'valign': 'vcenter',
  'fg_color': '#c44446',
  'font_color': 'white',
  'text_wrap': True})

formato_titulo_none = workbook.add_format({
  'bold': 1,
  'border': 1,
  'align': 'center',
  'valign': 'vcenter',
  'fg_color': 'white',
  'font_color': '#c44446',
  'text_wrap': False})

worksheet.set_row(0, 30, formato_titulo)
worksheet.set_column('A:Z', 12, formato_titulo_none)
writer.save()